apiVersion: v1
kind: Service
metadata:
    name: airbnb-booking
spec:
    selector:
        app: airbnb-booking
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
    type: ClusterIP
